---
- name: "Copy backend to remote"
  copy:
    src: /home/circleci/project/original.backend.tar
#    src: /home/pl704206/udacity/session4/final/original.backend.tar
    dest: /home/ubuntu/original.backend.tar

- name: "Extract backend"
  shell: |
    tar xvf /home/ubuntu/original.backend.tar

- name: "Install npm modules"
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    cd backend
    npm i

- name: "Build backend"
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    cd backend
    npm run build

- name: "Run backend"
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    cd backend/dist
    pm2 start main.js